### ISSUE TITLE
forecast first submission checklist

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-german-forecasts#2]
- [x] Decide on the amount of `EpiNow2` data to keep in git. Currently only the summarised estimates and plots are kept for reference/future work. 
- [x] Understand the date and data the forecast should be run on (i.e when is a week complete) and if the code is set up to do this correctly.
- [ ] Understand if there is truncation in the observed data and if so how many days are impacted by this (I assume this is not the case).
- [ ] Create a comparable cumulative forecast. To save issues this should probably be done alongside the human forecast effort based on the agreed up cases. As per point one this hinges on understanding when to start forecasting vs. to use observed data.
- [ ] Create a graph of forecast vs observed data for checking. Again probably makes sense to link this to the human-based forecast. 
- [x] How do we submit forecasts?

**Comment by nikosbosse** [comment]
Just looking over it very quick: 
- EpiNow2 data in git: not sure about this. Do we need any more than that? We do have the submissions as well, so I can't picture a case where we would need more, but I think you're better placed to make a decision on this as I don't know what else could be useful for future work
- date and data: Should be exactly as with the US. If I understand correctly we get all data Saturday at 2pm UK time (when the German Forecast Hub Travis Job runs) and epiweeks are from Saturday to Saturday. We can, however, use data from up to Monday for the first week. 
- cumulative forecast: What I will probably do is just add up quantiles. Will raise this discussion with the German and US Forecast Hub at some point as this probably not quite correct. If you have traces I think adding up values from the traces is ideal. 
- forecast vs. data plot: Will work on that the next week. For this week I suggest to just copy the "visualise submissions" code from the US forecast repo. Either can do that or you do
- I can probably take care of submission (will do that on Tuesday. But the system is again the same as for the US forecast Hub)

**Comment by seabbs** [comment]
- yes, less is good here. 

- sounds good using a run from today then. 

- I have the traces but not sure if this leads the quintiles of cumulative and incidence to disagree and that seems bad. For now map incidence to cumulative at the same time for both forecasts?

- 👍 

- I have never submitted for the US forecast hub 😄
